service: lambda-report-security-group

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:DescribeSecurityGroups
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeInstances
            - lambda:ListFunctions
          Resource: "*" 
        - Effect: Allow
          Action:
            - cloudwatch:PutMetricData
          Resource: "*"

functions:
  reportUnusedSecurityGroups:
    handler: handler.reportUnusedSecurityGroups
    timeout: 900
    description: "Report unused security groups and tracks them in CloudWatch"
    events:
      - schedule:
          rate: cron(0 7 ? * 2 *) # Every Monday at 07:00 UTC

package:
  individually: true